namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
    NEXT_PUBLIC_SITE_URL?: string;
    NEXT_PUBLIC_ENABLE_REACT_QUERY_DEVTOOLS?: "true" | "false";
    NEXT_PUBLIC_MEDIAMTX_RTMP_SERVER_URL?: string;
    NEXT_PUBLIC_MEDIAMTX_HLS_BASE_URL?: string;
    NEXT_PUBLIC_MEDIAMTX_STREAM_PATH?: string;

    SUPABASE_SERVICE_ROLE_KEY: string;
    LIVE_OVERLAY_TOKEN_SECRET: string;
    MEDIAMTX_API_BASE_URL?: string;
    VERCEL_URL?: string;
  }
}
