// 폼 검증과 필드 오류에 사용하는 문장형 메시지를 관리하는 상수

export const FORM_MESSAGE = {
  auth: {
    emailInvalid: "올바른 이메일 형식을 입력해주세요.",
    emailCheckFailed: "이메일 확인 중 오류가 발생했습니다.",
    emailAlreadyExists: "이미 가입된 이메일입니다.",
    passwordRequired: "비밀번호를 입력해주세요.",
    passwordMin: "비밀번호는 8자 이상이어야 합니다.",
    passwordLowercase: "비밀번호는 영문 소문자를 1개 이상 포함해야 합니다.",
    passwordUppercase: "비밀번호는 영문 대문자를 1개 이상 포함해야 합니다.",
    passwordDigit: "비밀번호는 숫자를 1개 이상 포함해야 합니다.",
    passwordSymbol: "비밀번호는 특수문자를 1개 이상 포함해야 합니다.",
    passwordMismatch: "비밀번호가 일치하지 않습니다.",
    nameMin: "이름은 2자 이상이어야 합니다.",
    nicknameMin: "닉네임은 2자 이상이어야 합니다.",
    nicknameMax: "닉네임은 10자 이하여야 합니다.",
    nicknameInvalidCharacters: "공백과 특수문자는 사용할 수 없습니다.",
    birthRequired: "생년월일을 입력해주세요.",
    birthInvalid: "올바른 생년월일 형식을 입력해주세요.",
    birthFuture: "생년월일은 오늘 이후 날짜를 선택할 수 없습니다.",
    phoneInvalid: "올바른 휴대전화번호 형식을 입력해주세요.",
    genderRequired: "성별을 선택해주세요.",
    otpInvalid: "인증 코드가 올바르지 않습니다.",
    currentPasswordInvalid: "현재 비밀번호가 올바르지 않습니다.",
    samePassword: "현재 비밀번호와 동일한 비밀번호는 사용할 수 없습니다.",
  },
  chatRoom: {
    titleRequired: "방 제목을 입력해주세요.",
    titleMax: (max: number) => `방 제목은 ${max}자 이하여야 합니다.`,
    descriptionMax: (max: number) => `방 설명은 ${max}자 이하여야 합니다.`,
    capacityRequired: "참여 가능 인원을 입력해주세요.",
    capacityInteger: "참여 가능 인원은 정수로 입력해주세요.",
    capacityMin: (min: number) => `최소 ${min}명 이상이어야 합니다.`,
    capacityMax: (max: number) => `최대 ${max}명까지 가능합니다.`,
  },
  channelChat: {
    chatScopeRequired: "채팅 참여 범위를 선택해주세요.",
    followerWaitInvalid: "선택할 수 있는 대기 시간을 골라주세요.",
    slowModeSecondsInvalid: "선택할 수 있는 채팅 간격을 골라주세요.",
    chatRuleTextMax: (max: number) => `안내문은 ${max}자 이하여야 합니다.`,
    forbiddenWordsMax: (max: number) => `금칙어는 최대 ${max}개까지 등록할 수 있습니다.`,
    forbiddenWordRequired: "금칙어를 입력해주세요.",
    forbiddenWordMax: (max: number) => `금칙어는 ${max}자 이하여야 합니다.`,
  },
  channelDonation: {
    minAmountRange: (min: number, max: number) =>
      `최소 후원 금액은 ${min.toLocaleString()}P 이상 ${max.toLocaleString()}P 이하여야 합니다.`,
    alertDurationInvalid: "선택할 수 있는 알림 표시 시간을 골라주세요.",
    alertSoundInvalid: "선택할 수 있는 알림음을 골라주세요.",
    alertVolumeRange: "알림 볼륨은 0부터 100 사이여야 합니다.",
    ttsRateInvalid: "선택할 수 있는 읽기 속도를 골라주세요.",
    ttsVolumeRange: "음성 볼륨은 0부터 100 사이여야 합니다.",
  },
} as const;
